In [3]:
import tensorflow as tf
import numpy as np

In [2]:
# define the data as constant
X = tf.constant([[0, 1], [2, 3]], tf.float32)
Y = tf.constant([[4], [5]], tf.float32)

# initialising the beta
beta = tf.Variable([[0.01], [0.01]], tf.float32)

# compute the residual
residuals = Y - tf.matmul(X, beta)

residuals


<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[3.99],
       [4.95]], dtype=float32)>

In [6]:
# rank-3 addition
images = np.random.rand(2, 4, 4)
transform = np.random.rand(2, 4, 4)

images = tf.constant(images, tf.float32)
transform = tf.constant(transform, tf.float32)

addition = tf.add(images, transform)
addition

<tf.Tensor: shape=(2, 4, 4), dtype=float32, numpy=
array([[[0.6630398 , 1.1542369 , 0.7178622 , 1.2149923 ],
        [1.3111463 , 1.2967427 , 1.6939186 , 1.5453889 ],
        [0.9880742 , 0.9602802 , 0.8544624 , 0.735728  ],
        [0.6819464 , 0.5682168 , 1.5388117 , 0.7973267 ]],

       [[0.69467163, 1.1786429 , 0.7274319 , 0.44603   ],
        [0.8026004 , 0.8900992 , 1.0139973 , 0.2869184 ],
        [1.4016023 , 0.93662703, 0.8432279 , 0.43697494],
        [1.3529558 , 0.44281995, 0.5284056 , 0.82471365]]], dtype=float32)>

In [7]:
# rank-4 addition
images = np.random.rand(2, 4, 4, 2)
transform = np.random.rand(2, 4, 4, 2)

images = tf.constant(images, tf.float32)
transform = tf.constant(transform, tf.float32)

addition = tf.add(images, transform)
addition


<tf.Tensor: shape=(2, 4, 4, 2), dtype=float32, numpy=
array([[[[0.6260457 , 1.1355646 ],
         [0.7329703 , 1.0553142 ],
         [0.72823435, 0.696879  ],
         [1.1101692 , 0.4862362 ]],

        [[0.10845772, 1.066894  ],
         [1.037339  , 0.46001235],
         [0.6056307 , 0.93011   ],
         [0.6908863 , 0.82703054]],

        [[1.1399679 , 0.81666285],
         [0.8624917 , 1.4848557 ],
         [1.42852   , 1.4586128 ],
         [0.477041  , 0.4836735 ]],

        [[0.5976449 , 0.9247024 ],
         [1.2424055 , 0.9814972 ],
         [1.1868832 , 1.0010691 ],
         [0.5724598 , 0.6680153 ]]],


       [[[0.43265182, 1.1151416 ],
         [0.8530179 , 0.51329917],
         [1.0413061 , 1.8850197 ],
         [0.33539575, 1.0818245 ]],

        [[1.4563037 , 0.12964375],
         [0.5606185 , 1.2314956 ],
         [1.6971716 , 0.46745118],
         [1.116049  , 1.6887681 ]],

        [[0.9788657 , 0.40156984],
         [1.0309037 , 0.38089266],
         [1.4804091 , 

In [22]:
tf.random.set_seed(1)

a = tf.random.normal([200])
b = tf.random.normal([200])

c = tf.tensordot(a, b, axes=1)
c.numpy()

-15.284364

In [25]:
images = tf.random.uniform((4, 16, 16))
transform = tf.random.normal((16, 16))

batch_matmul = tf.matmul(images, transform)
batch_elementwise = tf.multiply(images, transform)

print(batch_matmul)
print(batch_elementwise)


tf.Tensor(
[[[-5.3111033   2.20983    -0.8742196  ... -0.85024554  0.4490175
   -0.74632156]
  [-3.2046633   0.7722125  -1.6923969  ... -0.82774734 -4.1863966
   -1.2336454 ]
  [-6.5630174   3.1934006  -0.93205893 ... -0.7961356   1.1135936
    0.19270098]
  ...
  [-3.3219993   1.7427948   1.7976258  ... -1.7986567  -0.64670825
   -3.1097329 ]
  [-3.7355576   0.6526589  -1.5183977  ... -0.9278606  -0.49279517
   -0.43125725]
  [-2.1643248   1.2542639   0.65444696 ... -2.7711709  -2.7403457
   -0.2105838 ]]

 [[-2.0127294   2.535126    0.89846355 ... -1.6500188  -2.5639536
   -0.75288045]
  [-3.3018758   0.69258606 -2.7398138  ... -0.10634658 -3.0068936
   -1.0816443 ]
  [-4.8886495   0.34876508 -2.4191556  ...  1.1097413  -1.1159972
   -3.4196477 ]
  ...
  [-2.8874516   0.8230156  -1.8782297  ... -0.56005913 -0.8954675
   -0.03538597]
  [-2.6401346  -1.0849621  -2.9289787  ... -0.70453495 -0.5083778
   -2.6094048 ]
  [-3.692443   -0.17751288 -0.30683073 ... -2.1165001  -0.52137005
   -