# Numpy tutorial

In [1]:
import numpy as np 

In [9]:
data1 = [[[1, 2, 3, 4], [1, 2, 3, 4]], [[4, 3, 2, 1], [1, 2, 3, 4]]]
np.array(data1)

array([[[1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[4, 3, 2, 1],
        [1, 2, 3, 4]]])

In [10]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
# np.identity(6)
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [36]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

arr = arr.astype(np.float64)
print(arr.dtype)

int64
float64


In [38]:
numeric_string = np.array(['1.0', '3.2', '2.5'], dtype=np.string_)
numeric_string = numeric_string.astype(float)
numeric_string.dtype

dtype('float64')

In [39]:
arr[1: 3] = 6
new_arr = arr[1: 3]

In [40]:
new_arr[1] = 123
arr

array([  1.,   6., 123.,   4.])